exp:
  path: deeplabv2_GR1_val_COCO
  checkpoint_dir: checkpoint
  tensorboard_dir: runs
  preds: preds
  crf: pred_crf
  results: results
  logits: logits


EXP:
    ID: cocostuff164k
    OUTPUT_DIR: data

DATASET:

    root_dir: ./MSCOCO
    #txt_dir: ./VOCdevkit/VOC2012/ImageSets/Segmentation
    n_classes: 81
    crop_size: 321
    ignore_label: 255
    mean_bgr: [104.008, 116.669, 122.675]

    NAME: cocostuff164k
    ROOT: ./MSCOCO
    LABELS: ./data/datasets/coco/labels.txt
    N_CLASSES: 81
    IGNORE_LABEL: 255
    SCALES: [0.5, 0.75, 1.0, 1.25, 1.5]
    SPLIT:
        TRAIN: train2014
        VAL: val2014
        TEST:

DATALOADER:
    NUM_WORKERS: 0

IMAGE:
    MEAN:
        R: 122.675
        G: 116.669
        B: 104.008
    SIZE:
        BASE: # None
        TRAIN: 321
        TEST: 513

MODEL:
    NAME: DeepLabV2_ResNet101_MSC_SGR
    #NAME: DeepLabV2_ResNet101_MSC
    N_BLOCKS: [3, 4, 23, 3]
    ATROUS_RATES: [6, 12, 18, 24]
    INIT_MODEL: data/models/coco/deeplabv1_resnet101/caffemodel/deeplabv1_resnet101-coco.pth

SOLVER:
    BATCH_SIZE:
        TRAIN: 5
        TEST: 1
    ITER_MAX: 100000
    ITER_SIZE: 2
    ITER_SAVE: 5000
    ITER_TB: 100
    LR_DECAY: 10
    LR: 2.5e-4
    MOMENTUM: 0.9
    OPTIMIZER: sgd
    POLY_POWER: 0.9
    WEIGHT_DECAY: 5.0e-4
    AVERAGE_LOSS: 20

CRF:
    ITER_MAX: 10
    POS_W: 3
    POS_XY_STD: 1
    BI_W: 4
    BI_XY_STD: 67
    BI_RGB_STD: 3

DEEPLABV2:
    VISUAL_FEATURE_CHANNELS: 256
    INPUT_FEATURE_CHANNELS: 256